// IMPORTANTE: El orden aquí será el orden de las columnas
export const universities = {
    Utem: "utem.cl",
    UC: "uc.cl",
    UChile: "uchile.cl",
    UdeC: "udec.cl",
    USACH: "usach.cl",
    UAI: "uai.cl",
    PUCV: "pucv.cl",
    USM: "usm.cl",
    UACH: "uach.cl",
    Uandes: "andes.cl",
    UDP: "udp.cl",
    UDLA: "udla.cl",
    UST: "ust.cl",
    UTalca: "utalca.cl",
    UTA: "uta.cl",
    UFRO: "ufro.cl",
    UNAB: "unab.cl",
    UV: "uv.cl",
    UAutonoma: "uautonoma.cl",
};

export const keywords = [
    "universidad",
    "ingeniería civil industrial",
    // "ingeniería comercial",
    // "derecho",
    // "administración de empresas",
    // "carreras universitarias",
    // "ingeniería civil",
    // "ingeniería informatica",
    // "ingeniería industrial",
    // "ingenieía civil en minas",
    // "pedagogia",
    // "quimica y farmacia",
    // "psicología",
    // "ingeniería en comercio internacional",
    // "Arquitectura",
    // "ingenieria en biotecnologia",
    // "ingenieria civil biomedica",
    // "trabajo social",
    // "ingenieria civil en obras civiles",
    // "diseno en comunicacion visual",
    // "dibujante proyectista",
    // "ingenieria civil en mecanica",
    // "ingenieria civil electronica",
    // "ingenieria civil en ciencia de datos",
    // "administracion publica",
    // "ingenieria comercial",
    // "diseno industrial",
    // "ingenieria civil quimica",
    // "bibliotecologia y documentacion",
    // "ingenieria en construccion",
    // "ingenieria industrial",
    // "ingenieria civil matematica",
    // "ingenieria en alimentos",
    // "ingenieria civil en prevencion de riesgos",
    // "contador publico y auditor",
    // "ingenieria en gestion turistica",
    // "quimica industrial",
    // "ingenieria en geomensura",
    // "bachillerato en ciencias de la ingenieria",
    // "administracion publica",
];
