// IMPORTANTE: El orden aquí será el orden de las columnas
export const universities = {
    Utem: "utem.cl",
    UC: "uc.cl",
    UChile: "uchile.cl",
    UdeC: "udec.cl",
    USACH: "usach.cl",
    UAI: "uai.cl",
    PUCV: "pucv.cl",
    USM: "usm.cl",
    UACH: "uach.cl",
    Uandes: "andes.cl",
    UDP: "udp.cl",
    UDLA: "udla.cl",
    UST: "ust.cl",
    UTalca: "utalca.cl",
    UTA: "uta.cl",
    UFRO: "ufro.cl",
    UNAB: "unab.cl",
    UV: "uv.cl",
    UAutonoma: "uautonoma.cl",
};

export const keywords = [
    "universidad",
    "ingeniería",
    "carreras universitarias",
    "ingeniería civil industrial",
    "ingeniería comercial",
    "derecho",
    "administración de empresas",
    "ingeniería civil",
    "ingeniería informática",
    "ingeniería industrial",
    "ingeniería civil en minas",
    "pedagogía",
    "química y farmacia",
    "psicología",
    "ingeniería en comercio internacional",
    "Arquitectura",
    "ingeniería en biotecnología",
    "ingeniería civil biomédica",
    "trabajo social",
    "ingeniería civil en obras civiles",
    "diseño en comunicación visual",
    "dibujante proyectista",
    "ingeniería civil en mecánica",
    "ingeniería civil electrónica",
    "ingeniería civil en ciencia de datos",
    "administración pública",
    "ingeniería comercial",
    "diseño industrial",
    "ingeniería civil química",
    "bibliotecología y documentación",
    "ingeniería en construcción",
    "ingeniería industrial",
    "ingeniería civil matemática",
    "ingeniería en alimentos",
    "ingeniería civil en prevención de riesgos",
    "contador público y auditor",
    "ingeniería en gestión turística",
    "química industrial",
    "ingeniería en geomensura",
    "bachillerato en ciencias de la ingeniería",
    "administración pública",
];

/*
C4:U4,C5:U5,C6:U6,C7:U7,C8:U8,C9:U9,C10:U10,C11:U11,C12:U12,C13:U13,C14:U14,C15:U15,C16:U16,C17:U17,C18:U18,C19:U19,C20:U20,C21:U21,C22:U22,C23:U23,C24:U24,C25:U25,C26:U26,C27:U27,C28:U28,C29:U29,C30:U30,C31:U31,C32:U32,C33:U33,C34:U34,C35:U35,C36:U36,C37:U37,C38:U38,C39:U39,C40:U40,C41:U41,C42:U42,C43:U43,C44:U44
*/
